/*
 * This source file was generated by the Gradle 'init' task
 */
package programacion.aplicada;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appHasMenuOptions() {
        App classUnderTest = new App();
        assertTrue(classUnderTest.getMenuOptions().contains("0. Salir"),
                "menu should include exit option");
    }
}
